export BASH_SILENCE_DEPRECATION_WARNING=1

# Disable per session history, to force use of .bash_history file
touch ~/.bash_sessions_disable

# Number of lines to keep (1000 in this example)
echo "export HISTFILESIZE=10000" >> ~/.bash_profile

# Set how many commands to keep in the current session history list
echo "export HISTSIZE=800" >> ~/.bash_profile

# Set Prompt
PS1='\$\u@\h'
