syntax on
filetype on

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Enable use of the mouse for all modes
set mouse=a

" Disable auto comment
set formatoptions-=cr

" Turn on syntax highlighting
syntax on

" Visualize tabs and newlines
set listchars=tab:▸\ ,eol:¬
